name: Testing

on: push

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Django Unit Test
      run: |
        pip3 install --user -r requirements.txt
        python3 manage.py makemigrations
        python3 manage.py migrate
        coverage run --source='.' manage.py test
        coverage report
