name: Testing

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Django Test
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        pip install coverage
        python manage.py makemigrations users
        python manage.py migrate
        coverage run --source='.' manage.py test
        coverage report
