name: Testing

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Set Python version as needed
    
    - name: Install Dependencies
      run: |
        python -m pip install --user -r requirements.txt
        python -m pip install --user coverage

    - name: Run Migrations
      run: |
        python manage.py makemigrations users
        python manage.py migrate

    - name: Run Django Unit Tests with Coverage
      run: |
        coverage run --source='.' manage.py test
        coverage report
